### ISSUE TITLE
Cant login after deploying docker

### ISSUE THREAD

**Issue by xppx99** [ayufan/pve-backup-server-dockerfiles#1]
Hello, 

I'm trying to use your image. The deployment goes fine (without errors, at least), the webui (https://xyz:8007) loads fine, but then the credentials do not work: 

admin
pbspbs

Am I doing something wrong? 
Thanks

**Comment by ayufan** [comment]
@xppx99 Use Proxmox Authentication, instead of PAM.

**Comment by xppx99** [comment]
That was fast! Thanks. 

I also tried that, but without sucess:
![imagem](https://user-images.githubusercontent.com/52202278/123174109-860b0d00-d477-11eb-99d9-86d8f0b755ed.png)

Also tried with user "root". 

I see no erros in Portainer's log:
`PROXY: The proxmox-backup is not yet configured!
API: Starting...
PROXY: The proxmox-backup is not yet configured!
PROXY: The proxmox-backup is not yet configured!
PROXY: The proxmox-backup is not yet configured!
PROXY: Starting...`

Is there a way to enter

**Comment by ayufan** [comment]
The message is expected.

**Comment by ayufan** [comment]
I just tried, it works for me:

- user: admin
- pass: pbspbs
- realm: proxmox

**Comment by xppx99** [comment]
I manage to solve the problem, changin root password whithin console. 

Bont know why, but my instance shows no user admin:
![imagem](https://user-images.githubusercontent.com/52202278/123174914-ce76fa80-d478-11eb-927e-e398ac3accd4.png)

I used the command "roxmox-backup-manager user root@pam update --password new_password
and then I could login. 

I user your docker-compose file.

**Comment by ayufan** [comment]
I would ensure that data are persisted on volumes. Maybe the system you are using, did not copy over volume data? Basically these files: https://github.com/ayufan/pve-backup-server-dockerfiles/tree/master/pbs. Ensure that these files are in `/etc/proxmox-backup`.

Changing `root@pam` will not persist changes if you will ever update it.

Ref.: https://github.com/ayufan/pve-backup-server-dockerfiles/blob/master/docker-compose.yml#L9

**Comment by xppx99** [comment]
I though that was not relevant, I had my docker-compose volumes customized for my needs:
    volumes:
      - /volume1/docker/synology/pbs/etc:/etc/proxmox-backup
      - /volume1/docker/synology/pbs/etc:/var/log/proxmox-backup
      - /volume1/docker/synology/pbs/lib:/var/lib/proxmox-backup
      - backups:/backups

Because I do not understand well where those volumes are located, I mapped the folders, I'm kind of a noob with this, but thanks for your help. It's working fine now!

**Comment by ayufan** [comment]
Don’t share logs with etc :)
