### ISSUE TITLE
Error when docker-compose up

### ISSUE THREAD

**Issue by nath67** [ayufan/pve-backup-server-dockerfiles#10]
Hello,

When I try to run this image by using the docker-compose example or a handmade one, I get this error in a loop :
_pbs_1  | PROXY: Starting...
pbs_1  | Error: unable to create rrdb stat dir - EACCES: Permission denied_

**Comment by nath67** [comment]
I had to clone this repository, the image cannot be used alone.

**Comment by nath67** [comment]
The readme is not mentioning it, I reopened the issue to be sure.

**Comment by nath67** [comment]
This issue is not present on v2.0.7.

**Comment by ayufan** [comment]
The repo checkout is not required to run an image standalone.

**Comment by nath67** [comment]
As described here, you can temporarily fix it by making this as volume in the docker-compose to make it permanent :
rrdb:/var/lib/proxmox-backup/rrdb

https://forum.proxmox.com/threads/error-unable-to-create-rrdb-stat-dir-eacces-permission-denied-clean-pbs-v2-installation.99395/post-429144

**Comment by ayufan** [comment]
Oh. Yes, we should have this in `docker-compose.yml`.

**Comment by nath67** [comment]
Yes, the image sould do the chown temporarly or just do a "docker compose up -d && docker-compose down", then chown it manually.
... Or just wait because it's a bug ;)

**Comment by ayufan** [comment]
This should do the trick: https://github.com/ayufan/pve-backup-server-dockerfiles/commit/b6752a0f280b0b79a8cdacc370a42c05cf8cc2d2.

**Comment by ayufan** [comment]
The images are update with this fix. Re-pull them as they are under the same tag.
