### ISSUE TITLE
"/run/proxmox-backup/shmem" is not on tmpfs

### ISSUE THREAD

**Issue by woshilaiba** [ayufan/pve-backup-server-dockerfiles#11]
auth failed at the first login,
the error is 
2021-12-16T12:34:33+00:00: authentication failure; rhost=[::ffff:172.17.0.1]:57456 user=root@pam msg=path "/run/proxmox-backup/shmem" is not on tmpfs

the image is the latest prebuilt, 
"Created": "2021-11-30T15:37:34.74490427Z",

how to make "/run/proxmox-backup/shmem"  on a tmpfs?

**Comment by ayufan** [comment]
@woshilaiba https://github.com/ayufan/pve-backup-server-dockerfiles/blob/master/docker-compose.yml#L13

**Comment by woshilaiba** [comment]
> @woshilaiba https://github.com/ayufan/pve-backup-server-dockerfiles/blob/master/docker-compose.yml#L13

right, after i use the "docker-compose up -d" 
there is another error raised
"2021-12-16T15:04:55+00:00: authentication failure; rhost=[::ffff:192.168.66.99]:38584 user=admin@pam msg=open tmpfile in "/run/proxmox-backup/shmem" failed - EISDIR: Is a directory"
