### ISSUE TITLE
tmpfile in "/run/proxmox-backup/shmem" failed - EISDIR: Is a directory

### ISSUE THREAD

**Issue by woshilaiba** [ayufan/pve-backup-server-dockerfiles#13]
description： https://github.com/ayufan/pve-backup-server-dockerfiles/issues/11#issuecomment-995902984

**Comment by nath67** [comment]
Hello,

You have to remove the image and then you can rebuild the container :
_sudo docker image rm <image_name>_

You have to do this because it uses the same tag as the previous one before the fix so it doesn't pull the new one.

**Comment by ayufan** [comment]
Nope. You don't have to do it. Just do `docker-compose pull`.

**Comment by nath67** [comment]
> Nope. You don't have to do it. Just do `docker-compose pull`.

This also works 👍

**Comment by woshilaiba** [comment]
i just delete the old container with "docker rm [container id]", then docker pull image:latest
,and it is pulled to local.
after that i do the "docker-compose up -d" again, and the error occurred

**Comment by woshilaiba** [comment]
so strange!
**it works on ubuntu20.04**
"ubuntu2004 kernel 5.13.19-2"

but **does not work on synology6.1.7   kernel  3.10.102**

**Comment by woshilaiba** [comment]
> so strange! **it works on ubuntu20.04** "ubuntu2004 kernel 5.13.19-2"
> 
> but **does not work on synology6.1.7 kernel 3.10.102**

workaround:
there is a file named "config-versions" in shmem,
i copy it to the container on synology6.1.7, it works!!!
but don't know if there are other problems .

**Comment by woshilaiba** [comment]
**problems confirmed** , at least i can't modify the passwd for admin  from the web page, it will show an error "**Function not implemented (os error 38)**"
so just give up on synology6.1.7

**Comment by woshilaiba** [comment]
> **problems confirmed** , at least i can't modify the passwd for admin from the web page, it will show an error "**Function not implemented (os error 38)**" so just give up on synology6.1.7

”statx () was added to Linux in kernel 4.11“ ，so prompt this error.
