### ISSUE TITLE
Error with the GUI - ext-all.js - Uncaught TypeError: Cannot read property 'scope' of undefined

### ISSUE THREAD

**Issue by Power2All** [ayufan/pve-backup-server-dockerfiles#2]
Letting you know there is a error when opening certain places.
Attached screenshot of the error and how it looks like.
Any ad-blocker is disabled, works fine on a dedicated server, but on my raspberry pi I get this weird error.

![msedge_m1cOq7CGW6](https://user-images.githubusercontent.com/2010549/123292378-4abe1c00-d513-11eb-8049-d4272e50441d.png)

**Comment by ayufan** [comment]
@Power2All I noticed that. I saw that this is broken `ext4js` compilation as part of 1.1.9. You can for time being downgrade (without a problem) to 1.1.5. There's an associated tag on a image.

**Comment by Power2All** [comment]
@ayufan Awesome, will give that a try, thanks for the fast response :)

**Comment by ayufan** [comment]
I saw that there's 1.1.10. I might recompile again :)

**Comment by Power2All** [comment]
> I saw that there's 1.1.10. I might recompile again :)

Could you tell me the correct way to install it ?
I tried using "git checkout tags/v1.1.5" but I still get the issues with the javascript.
Maybe I'm doing something wrong ?

**Comment by ayufan** [comment]
@Power2All 

Instead of running `ayufan/proxmox-backup-server:latest`, run `ayufan/proxmox-backup-server:v1.1.5`.

Ref.: https://hub.docker.com/layers/ayufan/proxmox-backup-server/v1.1.5/images/sha256-ab7a62e0bc3c7b6bb89a76864bb5a52071ade876124102b340c0b75f4d45e642?context=explore

**Comment by Power2All** [comment]
> @Power2All
> 
> Instead of running `ayufan/proxmox-backup-server:latest`, run `ayufan/proxmox-backup-server:v1.1.5`.
> 
> Ref.: https://hub.docker.com/layers/ayufan/proxmox-backup-server/v1.1.5/images/sha256-ab7a62e0bc3c7b6bb89a76864bb5a52071ade876124102b340c0b75f4d45e642?context=explore

Oh, durp, right.
Thanks !

**Comment by ayufan** [comment]
It's building. I see that it works, but it will take a few moments to populate all.

**Comment by Power2All** [comment]
> It's building. I see that it works, but it will take a few moments to populate all.

Nice, let me know when the images are up, then I'll try and upgrade mine here as well.
I use the Pi 4B as backup station for my 64 core server, and later my 12 core machine as well.
If everything runs, I will also sync the local stored data with Google Drive, for multi-site location of backups.
Thanks again for your hard work as usual :)

**Comment by ayufan** [comment]
I use this on RockPro64 NAS. This works great, and this accepts backups from everywhere (and remote hosts) :)

**Comment by Power2All** [comment]
> I use this on RockPro64 NAS. This works great, and this accepts backups from everywhere (and remote hosts) :)

That's pretty neat :)
The Proxmox Backup server also runs fine on Synology SAN server, since my job had it for their backups.
Doing their whole infra, changing it to Proxmox (it was bare metal, lol), and switching everything to Docker Swarm using Portainer, Traefik and my own little GO web server to show maintenance page :)
Love it so far !

**Comment by ayufan** [comment]
I pushed `ayufan/proxmox-backup-server:v1.1.10` which seems to fix a problem. After I validate it will mark it as `:latest`.
