### ISSUE TITLE
PBS Version 2.2 - Release?

### ISSUE THREAD

**Issue by HeyWatchOutDude** [ayufan/pve-backup-server-dockerfiles#26]
Hi,

thanks for that awesome build and making it able to run on a RPI!😃 

Any idea when version 2.2 gets released?

**Comment by ayufan** [comment]
Well someday :)

**Comment by ayufan** [comment]
A lot of changes of 2.2 are already present in currently released builds.

**Comment by HeyWatchOutDude** [comment]
Ok thanks! 😃

**Comment by devzwf** [comment]
2.3 just release :)

**Comment by ayufan** [comment]
The 2.2 is published, and 2.3 is as well published (but not marked latest yet).
