### ISSUE TITLE
Odd issue, not sure if its expected?

### ISSUE THREAD

**Issue by mannp** [ayufan/pve-backup-server-dockerfiles#3]
Thanks for creating these docker files :)

I have create a backup share for the docker image,mounted at /backup, but in the proxmox backup gui, it can see all of my separate disks contained in my external raid disk array on the server?

I don't want proxmox backup touching those and wondered how it could be seeing them in the first place?

I have /backup mounted to an external share for the docker, but am not sure how to reference that from within proxmox backup; is it through a new datastore at /backup?

Thanks in advance :)

**Comment by ayufan** [comment]
Don't worry about this. You can see them, since `/sys` is shared with host, but PBS does not have any permission to do anything with them unless runs in `privileged: true`.

**Comment by mannp** [comment]
Thanks for the fast reply :) .... so is there a need to share /sys with the host?

**Comment by ayufan** [comment]
Yes.

**Comment by mannp** [comment]
> this is how container technology works by default.

Mhh, perhaps, but I am not able to see any disks in any other docker unless I specifically give it access. So it seems unless / unexpected to see that in this instance....

**Comment by ayufan** [comment]
How you check if you can see them?
