### ISSUE TITLE
Mesh central consent

### ISSUE THREAD

**Issue by Alainr69** [ayufan/pve-backup-server-dockerfiles#30]
Could it be possible to have an option for user consent but only for workstation.
Today i'm going to mesh central and change manually option for all new PC. 
Is there a script for this?

**Comment by ayufan** [comment]
What do you need?

**Comment by Alainr69** [comment]
I need to have an option when taking control to ask consent to user on Tactical RMM as it's possible on Mesh Central

**Comment by ayufan** [comment]
What is tactical RMM?
