### ISSUE TITLE
Hide "You do not have a valid subscription for this server. Please visit www.proxmox.com to get a list of available options."

### ISSUE THREAD

**Issue by n3roGit** [ayufan/pve-backup-server-dockerfiles#32]
Please hide "You do not have a valid subscription for this server. Please visit [www.proxmox.com](https://www.proxmox.com/en/proxmox-backup-server/pricing) to get a list of available options."

Its not important for us.

**Comment by ayufan** [comment]
@n3roGit I don't find this request morally acceptable for me. Closing it.

**Comment by DST73** [comment]
Promox itself has a quide how to change to "No-Subscription Repository"
https://pbs.proxmox.com/docs/installation.html
search for "[Proxmox Backup](https://www.proxmox.com/proxmox-backup-server) No-Subscription Repository"
I did this with my regular Proxmox setup 

So if they provide a guide by themself how to remove it I don't see what is not moral acceptable

**Comment by ayufan** [comment]
No, it is not the same. You will still see this message. You will not see if you upload proper license only.
