### ISSUE TITLE
What are the requirements for tmpfs volume / folder?

### ISSUE THREAD

**Issue by manoloxxl** [ayufan/pve-backup-server-dockerfiles#35]
Hi,

I've followed the official documentation from docker to create a (https://docs.portainer.io/user/docker/volumes/add) tmpfs volume and mapped the volume to /run in the container setting.

As in the documentation is written i can specify some settings for the tmpfs volume. In default it is "size=100m,uid=1000", but are there any requirements that i should configure for the volume, espsepcially the size?

Best Regards

Manuel

**Comment by ayufan** [comment]
Unsure. I always used default
