### ISSUE TITLE
backup register image failed: command error: EINVAL: Invalid argument

### ISSUE THREAD

**Issue by B5JohnSheridan** [ayufan/pve-backup-server-dockerfiles#36]
Hi,

I am trying to use the cool docker image on a QNAP ARM based NAS (TS-382X), however I have an issue when backing up VMs (but NOT CTs). I get the error

ERROR: VM 200 qmp command 'backup' failed - backup register image failed: command error: EINVAL: Invalid argument

I tried to run the container privileged and with all rights, but still get the error.

I found some similiar issues on the proxmox forum for a different NAS type:

https://forum.proxmox.com/threads/virtualized-pbs-with-shared-mount.100455/

However, I am successfully using a LXC container on a x64 based QNAP NAS which uses the same underlying file system.

In the above link, they talk about missing functions of the file system, however not which are missing and I was so far unable to determine more detail on this error.

Had anyone else this error and maybe has some additional ideas how to possibly circumvent it?

Would be sad to abandon the idea of using the NAS as PBS...

Thanks!

**Comment by bishopd** [comment]
I have the same problemon my QNAP. Did you solve the problem?

INFO: backup mode: snapshot
INFO: ionice priority: 7
INFO: creating Proxmox Backup Server archive 'vm/304/2024-02-07T16:47:07Z'
ERROR: VM 304 qmp command 'backup' failed - backup register image failed: command error: EINVAL: Invalid argument
INFO: aborting backup job

**Comment by B5JohnSheridan** [comment]
No, I gave up on this and just use a LXC container (debian:bookworm) and manuall install proxmox-backup-server on that with:

```
apt update
apt dist-upgrade
apt install wget
wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
echo "deb http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription" > /etc/apt/sources.list.d/pbs-no-subscription.list
apt update
apt install proxmox-backup-server
proxmox-backup-manager user create root@pbs --comment "Superuser" --password 12345
proxmox-backup-manager acl update / Admin --auth-id root@pbs
proxmox-backup-manager user update root@pam --enable 0
```
Also, comment out the deb line in `/etc/apt/sources.list.d/pbs-enterprise.list`. Also, as the newest Container Station does not allow port forwards into LXCs, I had to SSH into the NAS and issue

```
lxc config device add pbs port8007 proxy listen=tcp:<ip-of-nas>:8007 connect=tcp:127.0.0.1:8007
```

Afterwards you can login via https://<ip-of-nas>:8007, using PBS (not PAM) as root with the password 12345.

This works nicely, however, I need to use a subfolder of the storage, e.g. if I use `/shared/folder` and `/mnt/pbs` inside the LXC, I need to put the datastore in `/mnt/pbs/pbs` and let the proxmox-backup-server create the `pbs` folder to have the correct permissions. Otherwise, datastore creation fails.

**Comment by bishopd** [comment]
tks i will try.

**Comment by LexPanov** [comment]
Hi! I ran into the same problem.
Unfortunately, on QNAP TS-832X (`Linux 4.2.8 #1 SMP Mon May 26 04:39:53 CST 2025 aarch64 GNU/Linux`) this issue cannot be fixed because the NAS runs a kernel with `PAGESIZE=65536`.
Proxmox Backup Server requires a 4K page size; otherwise, fixed index creation fails with EINVAL and the backup ends without the finished flag.
Unlike Raspberry Pi, as mentioned in wofferl/proxmox-backup-arm64#40, QNAP does not provide an alternative 4K page size kernel.
Since containers (Docker/LXC) use the host kernel, the only workaround is to run PBS on a different machine with a 4K kernel and store backups on the NAS over NFS/SMB/iSCSI.
