### ISSUE TITLE
Missing docker configuration file in latest-arm64v8?

### ISSUE THREAD

**Issue by mikkelsiggaard** [ayufan/pve-backup-server-dockerfiles#41]
I'm not sure if I'm noobing hard at Docker, but I have pulled [this image](https://hub.docker.com/layers/ayufan/proxmox-backup-server/latest-arm64v8/images/sha256-1dfcb8b87d2bd1a4774ba39e0233a2e86e5f9560ebe5a2a1b722d38131b6e64e?context=explore) 

Following the guide, running `docker compose up -d` gets me this result: `no configuration file provided: not found`

Invoking `docker images` gets me this result. 

```
REPOSITORY                     TAG              IMAGE ID       CREATED       SIZE
ayufan/proxmox-backup-server   latest-arm64v8   8385a2b9ec77   6 weeks ago   1.31GB
```

I'm suspecting that there is no docker-compose.yml file and unsure if this is expected (and I just know the correct proces)  or my use case is just undocumented? 

Trying to install this on a Raspberry Pi 4 with Raspbian 11 (Bullseye).

**Comment by pjpm15** [comment]
Have you created the yml file? You have to create a docker-compose.yml file. Then copy the contents from this and setup your volumes. https://github.com/ayufan/pve-backup-server-dockerfiles/blob/master/docker-compose.yml

**Comment by dth202** [comment]
I too am getting problems trying to run this image in my raspberry pi 4. I am able to run the compose file up, but the container just sit there restarting with error code 159. 

![image](https://github.com/ayufan/pve-backup-server-dockerfiles/assets/1136182/e62d4813-82e1-4622-8b2e-f38a0329792f)

**Comment by dth202** [comment]
Exit code 159 is referring to the missing Arch when trying to start the docker container. 
If you try and run the container manually with a simple docker run command on the image I get:

WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v8) and no specific platform was requested

I thought I had verified that I had the 64 bit version of raspbian installed, but I guess it looks like I have the 32 bit...

root@pi401:~# getconf LONG_BIT
32

**Comment by mikkelsiggaard** [comment]
So the hardware is 64 bit capable, but Raspbian is running the 32 bit Linux kernel? 

lscpu
`Architecture:                    aarch64`

getconf LONG_BIT
`32`

I'm pretty sure I installed Raspbian (Debian 11 - Bullseye) 64-bit. 
So is it actually possible to get the 64 bit Linux kernel running on a Raspberry Pi (question for tomorrow).

**Comment by mikkelsiggaard** [comment]
@dth202 I solved the 159 error by installing OS from scratch. Turns out I had installed "2023-05-03-raspios-bullseye-**armhf**-lite.img.xz". 

By installing "2023-05-03-raspios-bullseye-**arm64**-lite.img.xz" it now reports as 64 bit when calling getconf LONG_BIT. Maybe that is your issue too?

**Comment by ayufan** [comment]
Yes, you need arm64 system. The `armhf` will not work, since PBS requires 64 bit all the time.
