### ISSUE TITLE
PBS 3.0.2 - desn't start

### ISSUE THREAD

**Issue by SAOPP** [ayufan/pve-backup-server-dockerfiles#43]
Hi!

Faced with the next after update to the latest container v3.0.2:

```
rm: cannot remove '/etc/proxmox-backup/*.lock': No such file or directory
rm: cannot remove '/etc/proxmox-backup/.*.lck': No such file or directory
/run is a mountpoint
PROXY: The proxmox-backup is not yet configured!
API: Starting...
/var/lib/proxmox-backup is a mountpoint
/etc/proxmox-backup is a mountpoint
/var/log/proxmox-backup is a mountpoint
thread 'main' panicked at /src/proxmox-backup/build/debian/cargo_home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:13:
OS can't spawn worker thread: Operation not permitted (os error 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This logs I get after deploy a new instance (without current 2.4.1 update) also.

I don't c any breaking changes at this update, but a fresh container have the same behaviour... Someone can suggestion? Maybe host system or something.

**Comment by SAOPP** [comment]
I think it's 'coz my old omv server, I got old docker and kernel.

![image](https://github.com/ayufan/pve-backup-server-dockerfiles/assets/5647009/4acce794-7b5f-4449-a051-81aa8ee39bb2)

**Comment by ayufan** [comment]
Likely. Just update kernel and it should do the trick.
