### ISSUE TITLE
How do I change the default admin/pbspbs credentials?

### ISSUE THREAD

**Issue by rogierlommers** [ayufan/pve-backup-server-dockerfiles#45]
Maybe a bit of a stupid question, but how do I change the default admin / pbspbs credentials?

**Comment by ayufan** [comment]
From web interface: you can create new account, or change password.

**Comment by rogierlommers** [comment]
I TOTALLY overlooked that. Sorry!

For future reference:

<img width="1067" alt="Screenshot 2024-01-07 at 10 49 54" src="https://github.com/ayufan/pve-backup-server-dockerfiles/assets/3907131/ac80200a-2911-4519-9e11-4db16e606689">
