### ISSUE TITLE
3.1.2 image have a ui issue

### ISSUE THREAD

**Issue by ifooth** [ayufan/pve-backup-server-dockerfiles#46]
## screenshot
ui loading
<img width="1747" alt="image" src="https://github.com/ayufan/pve-backup-server-dockerfiles/assets/1853121/23407b65-9b64-48a6-ad1d-478bce4ea31c">

console err
<img width="681" alt="image" src="https://github.com/ayufan/pve-backup-server-dockerfiles/assets/1853121/3a55c174-c132-4f60-90bc-1015d296d8ca">

kernel version
<img width="960" alt="image" src="https://github.com/ayufan/pve-backup-server-dockerfiles/assets/1853121/a36441e0-44c6-4be0-adce-617b2050c0e0">

Can it be fix please? thank you

**Comment by dwyeraidan** [comment]
I also have same issue.
