### ISSUE TITLE
2 out of 2 hunks FAILED

### ISSUE THREAD

**Issue by caraar12345** [ayufan/pve-backup-server-dockerfiles#5]
Hey folks, trying to build from the `Dockerfile` and it's failing at step 11:

```
Step 11/39 : RUN /scripts/apply-patches.bash /patches/server/*.patch
 ---> Running in 9ec6da8051c6
/patches/server/proxmox-backup.patch => proxmox-backup...
patching file Cargo.toml
Hunk #1 FAILED at 52.
Hunk #2 FAILED at 79.
2 out of 2 hunks FAILED -- saving rejects to file Cargo.toml.rej
patching file debian/proxmox-backup-server.install
patching file debian/rules
The command '/bin/sh -c /scripts/apply-patches.bash /patches/server/*.patch' returned a non-zero code: 1
```

Unfortunately I'm not a Rust person 😅

Any ideas?

**Comment by ayufan** [comment]
You need to build for specific version. The dev might not work unless
patches are fixed.

**Comment by caraar12345** [comment]
Ah awesome - that was it! Built for v1.1.10 and it's working great 😊 

Didn't realise it would compile the whole of PBS though so I've run it on a Raspberry Pi....⌛

**Comment by ayufan** [comment]
The images are already prebuilt. So, you don’t even have to do it :)
