### ISSUE TITLE
Admin Console?

### ISSUE THREAD

**Issue by BenSanborn** [ayufan/pve-backup-server-dockerfiles#53]
Hey there,

I'm a linux newbie in general, especially when it comes to proxmox. When logged in as admin there is no shell option, and I'd really like to run the command from https://tteck.github.io/Proxmox/#proxmox-backup-server-post-install to remove the annoying subscription nag.

What am I doing wrong, or is this not possible on the dockerized version?

**Comment by jcormier** [comment]
You can get access to the shell inside the docker by running ```docker exec -it <container id> bash```

**Comment by BenSanborn** [comment]
Thank you much!
