### ISSUE TITLE
Adding notifications (ie bump to 3.2)

### ISSUE THREAD

**Issue by dwyeraidan** [ayufan/pve-backup-server-dockerfiles#54]
hey there,

Thanks for this project!

Version 3.2 has added notification functionality - would love to see this docker image updated with the newer version?

Thanks very much,

Aidan

**Comment by momuskk** [comment]
In 3.2 there is also new option like "change-detection-mode".

**Comment by ayufan** [comment]
Duplicate of https://github.com/ayufan/pve-backup-server-dockerfiles/issues/54
