### ISSUE TITLE
Error Log: Failed to connect to bus: Host is down 

### ISSUE THREAD

**Issue by codersaur** [ayufan/pve-backup-server-dockerfiles#57]
I'm seeing the following error message spamming my PBS container logs (typically repeated 50 times in a few seconds, possibly correlated with then I connect to the Web UI):
`Failed to connect to bus: Host is down `

I haven't noticed any issues with the operation of PBS, so wondering what the cause of this message is, if there's anything that can be done to prevent it, and/or whether it can be safely ignored?

**Comment by ayufan** [comment]
Do you see it anymore also on 3.3.2?

**Comment by codersaur** [comment]
> Do you see it anymore also on 3.3.2?

No, not yet, which is somewhat promising, but I've only been running 3.3.2 for 24hrs so far. I will keep monitoring and report back in a few days.

**Comment by codersaur** [comment]
Error hasn't reoccurred since upgrading to v3.3.2 so closing this.... thanks.
