### ISSUE TITLE
How to configure smtp?

### ISSUE THREAD

**Issue by kadrim** [ayufan/pve-backup-server-dockerfiles#7]
on the docker-host i have a working postfix configured and running.

can i somehow put that to use or do i have to add a postfix to the docker-container? what would be the best approach so i can send the system-notifications?

**Comment by ayufan** [comment]
Unfortunately not. You would have to run postfix in a container. That would have its own mail server.

Some info is explained here: https://serverfault.com/questions/631941/send-mail-from-docker-container-with-hosts-postfix

**Comment by kadrim** [comment]
thanks for the heads up! Maybe i will then add some docker-compose magic to the setup

**Comment by n3roGit** [comment]
@kadrim could you please provide your solution?
