### ISSUE TITLE
read_meminfo failed - unable to read ...pages_sharing"

### ISSUE THREAD

**Issue by caraar12345** [ayufan/pve-backup-server-dockerfiles#8]
Hey there! I've been using PBS through Docker for a while now with no issues, but today I can't get it to start.

It's repeatedly spitting out the below to the logs but not booting up.

`read_meminfo failed - unable to read "/sys/kernel/mm/ksm/pages_sharing" - No such file or directory (os error 2)`

Any idea as to what may be causing this?

I'm running the latest debug version (although it was showing up on `:latest` too) on a Pi 4 with Debian Buster.

**Comment by sysrq-reisub** [comment]
It starts for me, that error appears only into PBS when I try to view some graphs

**Comment by dorianim** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/30153207/153271746-fda39811-a16e-4656-b3de-6b2a8da147d6.png)

Running on a raspberry pi 3b+  on 64bit raspberrypi os.

**Comment by dorianim** [comment]
Is it possible, that this is related to [RaspberrypiOS not supporting KMS](https://github.com/raspberrypi/linux/issues/1238)?

**Comment by dorianim** [comment]
This may be helpful: https://github.com/wofferl/proxmox-backup-arm64/pull/5

**Comment by ayufan** [comment]
Since this is docker container. Just bind-mount empty file, this should silence this warning very well.

```
volumes:
  - /dev/null:/sys/kernel/mm/ksm/pages_sharing:ro
```

**Comment by dorianim** [comment]
Unfortunately, the docker container does not start with that setting added:
![image](https://user-images.githubusercontent.com/30153207/153279496-99ef6a45-1dd6-4111-b082-516fca4fb726.png)

**Comment by dorianim** [comment]
The error also appears on the dashboard:
![image](https://user-images.githubusercontent.com/30153207/153287576-b0ccebaf-cc74-42c9-8a5e-59747253ecc5.png)

**Comment by dorianim** [comment]
Would it be possible to apply the patch from https://github.com/wofferl/proxmox-backup-arm64/pull/5 ?
That would solve the problem in a clean way in my opinion :)

**Comment by ayufan** [comment]
Will do in next round :)

**Comment by ayufan** [comment]
@dorianim 

For time being this should do the trick:

```yaml
   volumes:
      - /tmp/pbs-mm:/sys/kernel/mm
    command:
      /bin/bash -c 'mkdir -p /sys/kernel/mm/ksm; echo 0 > /sys/kernel/mm/ksm/pages_sharing; exec runsvdir /runit'
```

**Comment by dorianim** [comment]
Yes, that word, thank you!

Also, thanks a lot for wrapping this up! It is the perfect solution and exactly what I was looking for for a long time :+1:

**Comment by ayufan** [comment]
@dorianim @caraar12345 You might check `v2.1.5` with a fix: https://hub.docker.com/r/ayufan/proxmox-backup-server.

**Comment by dorianim** [comment]
Works for me! :smile:
